### PR TITLE
fix(react): fixed button can't be decendant error

### LINKED ISSUE #73: <button> cannot be a descendant of <button>
### Severity

🟢 Low: Minor inconvenience

### Version

Latest

### Steps to Reproduce

1. Open Consent Manager Dialog

### Expected Behavior

Error not to appear

### Actual Behavior

```
Error: In HTML, <button> cannot be a descendant of <button>.
This will cause a hydration error.

  ...
    <AccordionItem ref={null} value="necessary" className="kf-accordi..." style={undefined}>
      <AccordionItemProvider scope={undefined} open={false} disabled={undefined} triggerId="radix-:re:">
        <Collapsible data-orientation="vertical" data-state="closed" __scopeCollapsible={{...}} className="kf-accordi..." ...>
          <CollapsibleProvider scope={{...}} disabled={undefined} contentId="radix-:rf:" open={false} ...>
            <Primitive.div data-state="closed" data-disabled={undefined} data-orientation="vertical" ...>
              <div data-state="closed" data-disabled={undefined} data-orientation="vertical" className="kf-accordi..." ...>
                <AccordionTrigger themeKey="consent-ma..." data-testid="consent-ma...">
                  <AccordionTrigger ref={null} data-testid="consent-ma..." className="kf-accordi..." style={undefined}>
                    <AccordionCollectionItemSlot scope={undefined}>
                      <Slot data-radix-collection-item="" ref={function}>
                        <SlotClone data-radix-collection-item="" ref={function}>
                          <CollapsibleTrigger aria-disabled={undefined} data-orientation="vertical" id="radix-:re:" ...>
                            <Primitive.button type="button" aria-controls="radix-:rf:" aria-expanded={false} ...>
>                             <button
>                               type="button"
>                               aria-controls="radix-:rf:"
>                               aria-expanded={false}
>                               data-state="closed"
>                               data-disabled={undefined}
>                               disabled={undefined}
>                               aria-disabled={undefined}
>                               data-orientation="vertical"
>                               id="radix-:re:"
>                               data-testid="consent-manager-widget-accordion-trigger-necessary"
>                               className="kf-accordion-trigger"
>                               style={{}}
>                               data-radix-collection-item=""
>                               onClick={function handleEvent}
>                               ref={function}
>                             >
                                <Box>
                                ...
                                  <SwitchProvider scope={undefined} checked={true} disabled={true}>
                                    <Primitive.button type="button" role="switch" aria-checked={true} ...>
>                                     <button
>                                       type="button"
>                                       role="switch"
>                                       aria-checked={true}
>                                       aria-required={undefined}
>                                       data-state="checked"
>                                       data-disabled=""
>                                       disabled={true}
>                                       value="on"
>                                       onClick={function handleEvent}
>                                       onKeyUp={function onKeyUp}
>                                       onKeyDown={function onKeyDown}
>                                       data-testid="consent-manager-widget-switch-necessary"
>                                       className="kf-switch kf-switch-root"
>                                       style={undefined}
>                                       ref={function}
>                                     >
                                    ...
                ...

    at createUnhandledError (http://localhost:3000/_next/static/chunks/bb398_next_dist_client_936642._.js:689:49)
    at handleClientError (http://localhost:3000/_next/static/chunks/bb398_next_dist_client_936642._.js:856:56)
    at console.error (http://localhost:3000/_next/static/chunks/bb398_next_dist_client_936642._.js:991:56)
    at validateDOMNesting (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:1804:356)
    at completeWork (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:7273:25)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:631:20)
    at completeUnitOfWork (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:8020:23)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:7957:28)
    at workLoopSync (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:7847:40)
    at renderRootSync (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:7830:13)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:7565:211)
    at performSyncWorkOnRoot (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:8402:9)
    at flushSyncWorkAcrossRoots_impl (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:8326:245)
    at processRootScheduleInMicrotask (http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:8343:9)
    at http://localhost:3000/_next/static/chunks/bb398_next_dist_compiled_react-dom_fe1e30._.js:8413:126
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by KayleeWilliams**
## Related Issue
Fixes #73 

## Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ Enhancement (improves existing functionality)
- [ ] 🚀 New feature
- [ ] 💥 Breaking change (requires migration)
- [ ] 📚 Documentation
- [ ] 🏗️ Refactor (no functional changes)
- [ ] 🎨 Style (formatting, no code changes)
- [ ] ⚡ Performance

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `ConsentManagementIcon` component for branding representation.
  - Added a new theme key for customizing the accordion trigger.

- **Style**
  - Enhanced the visual layout of the consent management accordion, ensuring a clearer grouping of consent options for a cleaner interface.
  - Updated styles for the branding link and accordion trigger to improve layout and responsiveness.

- **Documentation**
  - Updated documentation to reflect new theme properties and customization options for the consent manager widget.

### CODE REVIEW

File: packages/react/src/consent-manager-widget/atoms/accordion.tsx [hunk 1]
```diff
@@ -79,18 +79,26 @@ const ConsentManagerWidgetAccordionItems = () => {
 			key={consent.name}
 			themeKey={`consent-manager-widget.accordion.item-${consent.name}`}
 		>
-			<ConsentManagerWidgetAccordionTrigger
-				themeKey="consent-manager-widget.accordion.trigger"
-				data-testid={`consent-manager-widget-accordion-trigger-${consent.name}`}
+			<div
+				style={{
```
Comment (BurnedChris) [inline packages/react/src/consent-manager-widget/atoms/accordion.tsx]: **suggestion (blocking):** can we do it without adding another class in? if not can we rename it and make it a box and allow string's and styles to be passed in.
